using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace LlmCaddy.Models
{
    [Table("AnonymousProxyBackups")]
    public class AnonymousProxyBackup
    {
        /// <summary>
        /// Gets or sets the unique tracking identifier generated by the client browser's local crypto storage routine.
        /// </summary>
        [Key]
        [Required]
        [MaxLength(100)]
        [Column("ProxyClientId", TypeName = "varchar(100)")]
        public string ProxyClientId { get; set; } = null!;

        /// <summary>
        /// Gets or sets the serialized binary representation byte block of the user's isolated local SQLite schema file.
        /// Maps cleanly to a 'bytea' column type inside a PostgreSQL cluster database structure.
        /// </summary>
        [Required]
        [Column("SqliteBackupBlob", TypeName = "bytea")]
        public byte[] SqliteBackupBlob { get; set; } = null!;

        /// <summary>
        /// Gets or sets the absolute system universal coordinated date stamp tracking when this snapshot sync loop was last completed.
        /// </summary>
        [Required]
        [Column("LastSyncTime", TypeName = "timestamp with time zone")]
        public DateTime LastSyncTime { get; set; }

        public string MnemonicPhrase { get; set; }
    }
}
